### ISSUE TITLE
Can't install module - ref-napi issue?

### ISSUE THREAD

**Issue by tubes41** [inwaar/node-red-contrib-dahua-device#2]
Unable to install in the latest version of node-red:

```
2019-08-12T02:24:51.946Z Install : node-red-contrib-dahua-device 0.0.2

2019-08-12T02:24:52.067Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-dahua-device@0.0.2
2019-08-12T02:30:08.150Z [out] 
2019-08-12T02:30:08.150Z [out] > ref-napi@1.4.0 install /config/node-red/node_modules/net-keepalive/node_modules/ref-napi
2019-08-12T02:30:08.150Z [out] > node-gyp rebuild
2019-08-12T02:30:08.150Z [out] 
2019-08-12T02:30:25.129Z [err] gyp
2019-08-12T02:30:25.135Z [err]  
2019-08-12T02:30:25.137Z [err] ERR!
2019-08-12T02:30:25.138Z [err]  
2019-08-12T02:30:25.139Z [err] build error
2019-08-12T02:30:25.140Z [err]  
2019-08-12T02:30:25.145Z [err] gyp
2019-08-12T02:30:25.146Z [err]  
2019-08-12T02:30:25.147Z [err] ERR!
2019-08-12T02:30:25.148Z [err]  
2019-08-12T02:30:25.149Z [err] stack
2019-08-12T02:30:25.150Z [err]  Error: not found: make
2019-08-12T02:30:25.151Z [err] gyp
2019-08-12T02:30:25.152Z [err]  
2019-08-12T02:30:25.152Z [err] ERR!
2019-08-12T02:30:25.153Z [err]  
2019-08-12T02:30:25.154Z [err] stack
2019-08-12T02:30:25.154Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2019-08-12T02:30:25.155Z [err] gyp
2019-08-12T02:30:25.155Z [err]  
2019-08-12T02:30:25.156Z [err] ERR!
2019-08-12T02:30:25.157Z [err]  
2019-08-12T02:30:25.157Z [err] stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2019-08-12T02:30:25.158Z [err] gyp ERR! 
2019-08-12T02:30:25.158Z [err] stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2019-08-12T02:30:25.158Z [err] gyp 
2019-08-12T02:30:25.159Z [err] ERR! 
2019-08-12T02:30:25.159Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2019-08-12T02:30:25.159Z [err] gyp 
2019-08-12T02:30:25.160Z [err] ERR!
2019-08-12T02:30:25.160Z [err]  stack
2019-08-12T02:30:25.160Z [err]      at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2019-08-12T02:30:25.160Z [err] gyp
2019-08-12T02:30:25.160Z [err]  
2019-08-12T02:30:25.161Z [err] ERR! 
2019-08-12T02:30:25.161Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2019-08-12T02:30:25.161Z [err] gyp 
2019-08-12T02:30:25.161Z [err] ERR!
2019-08-12T02:30:25.162Z [err]  stack
2019-08-12T02:30:25.162Z [err]      at FSReqWrap.oncomplete (fs.js:153:21)
2019-08-12T02:30:25.163Z [err] gyp
2019-08-12T02:30:25.164Z [err]  ERR! 
2019-08-12T02:30:25.164Z [err] System Linux 4.14.98-v7
2019-08-12T02:30:25.165Z [err] gyp
2019-08-12T02:30:25.166Z [err]  ERR! 
2019-08-12T02:30:25.166Z [err] command
2019-08-12T02:30:25.167Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-08-12T02:30:25.167Z [err] gyp 
2019-08-12T02:30:25.167Z [err] ERR! 
2019-08-12T02:30:25.168Z [err] cwd
2019-08-12T02:30:25.168Z [err]  /config/node-red/node_modules/net-keepalive/node_modules/ref-napi
2019-08-12T02:30:25.168Z [err] gyp 
2019-08-12T02:30:25.169Z [err] ERR! 
2019-08-12T02:30:25.169Z [err] node -v v10.16.0
2019-08-12T02:30:25.169Z [err] gyp
2019-08-12T02:30:25.169Z [err]  ERR!
2019-08-12T02:30:25.170Z [err]  
2019-08-12T02:30:25.170Z [err] node-gyp -v v3.8.0
2019-08-12T02:30:25.171Z [err] gyp
2019-08-12T02:30:25.171Z [err]  ERR! 
2019-08-12T02:30:25.172Z [err] not ok 
2019-08-12T02:30:43.087Z [err] npm
2019-08-12T02:30:43.088Z [err]  
2019-08-12T02:30:43.089Z [err] ERR!
2019-08-12T02:30:43.090Z [err]  
2019-08-12T02:30:43.091Z [err] code
2019-08-12T02:30:43.092Z [err]  ELIFECYCLE
2019-08-12T02:30:43.094Z [err] npm
2019-08-12T02:30:43.094Z [err]  ERR!
2019-08-12T02:30:43.095Z [err]  errno 1
2019-08-12T02:30:43.106Z [err] npm
2019-08-12T02:30:43.107Z [err]  ERR! ref-napi@1.4.0 install: `node-gyp rebuild`
2019-08-12T02:30:43.107Z [err] npm 
2019-08-12T02:30:43.107Z [err] ERR! Exit status 1
2019-08-12T02:30:43.108Z [err] npm
2019-08-12T02:30:43.109Z [err]  ERR!
2019-08-12T02:30:43.109Z [err]  
2019-08-12T02:30:43.109Z [err] npm
2019-08-12T02:30:43.109Z [err]  ERR! Failed at the ref-napi@1.4.0 install script.
2019-08-12T02:30:43.110Z [err] npm ERR!
2019-08-12T02:30:43.110Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2019-08-12T02:30:43.598Z [err] 
2019-08-12T02:30:43.599Z [err] npm ERR!
2019-08-12T02:30:43.599Z [err]  A complete log of this run can be found in:
2019-08-12T02:30:43.600Z [err] npm ERR!
2019-08-12T02:30:43.600Z [err]      /root/.npm/_logs/2019-08-12T02_30_43_398Z-debug.log
2019-08-12T02:30:43.654Z rc=1
```

**Comment by inwaar** [comment]
Hi tubes41, could you try to install `make` command and try again?
