### ISSUE TITLE
can't install the node on hassio add on

### ISSUE THREAD

**Issue by emiosteo** [inwaar/node-red-contrib-dahua-device#4]
hi 
I can't install the node in hassio
I use nod red add on

Failed to install: node-red-contrib-dahua-device
Install failed
Check the log for more information

**Comment by inwaar** [comment]
could you please attach the logs?

**Comment by FrankZZ** [comment]
```
> ref-napi@1.4.0 install /opt/node_modules/net-keepalive/node_modules/ref-napi
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 4.15.0-91-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/node_modules/net-keepalive/node_modules/ref-napi
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref-napi@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref-napi@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-21T17_50_14_254Z-debug.log
```

**Comment by FrankZZ** [comment]
I think the solution would be to specify system packages in system-packages of the node-red hassio addon config. Will try that

**Comment by FrankZZ** [comment]
I've fixed it by adding
```
system_packages:
  - musl
  - build-base
```

in the hassio addon config of Node-RED
